# NLWeb Configuration
# This file contains settings specific to the NLWeb functionality

# Comma-separated list of allowed sites, if you have multiple sites
# in your store and want to restrict search to some sites. Defaults 
# to all, for now.
#sites: "yoursite"

# Data folders for JSON files and embeddings
data_folders:
  json_data: "../data/json"
  json_with_embeddings: "../data/json_with_embeddings"

# Chatbot formatting instructions
chatbot_instructions:
  # Instructions for formatting search results
  search_results: >
    IMPORTANT FORMATTING INSTRUCTION: When presenting these results to the user:
    1. For each item in the 'results' array, format the 'name' field as a hyperlink using the
       'url' field as the link destination. For example, convert: 
         name: 'Open Studio', url: 'https://example.com/event' 
       to: 
         [Open Studio](https://example.com/event)
    2. If the item has an 'image' field (which may be in the value of the schema_object field of the item), include the image in your response using markdown image syntax:
         ![Event Name](image_url)
    3. Include relevant details like location, date, and description after the link.
    Every result should be presented with the name as a clickable link, an image if available,
    and key information about the event.