const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {createRequire}=require('node:module');
const root=path.resolve(__dirname,'..');
const {JSDOM}=createRequire(path.join(root,'tools/library-apps/package.json'))('jsdom');
const folder=path.join(root,'library/apps/project-viability-navigator');
const clone=x=>JSON.parse(JSON.stringify(x));
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-10,`${a} != ${b}`);
function ui(t,{graph=false}={}){const dom=new JSDOM(fs.readFileSync(path.join(folder,'index.html'),'utf8'),{url:'https://example.test/library/apps/project-viability-navigator/',runScripts:'outside-only',pretendToBeVisual:true});dom.window.TextEncoder=TextEncoder;if(graph)dom.window.eval(fs.readFileSync(path.join(folder,'vendor/d3.v7.9.0.min.js'),'utf8'));dom.window.eval(fs.readFileSync(path.join(folder,'app.js'),'utf8'));t.after(()=>{dom.window.ViabilityNavigator.destroy();dom.window.close();});const d=dom.window.document;return{dom,d,m:dom.window.ViabilityNavigator,click:id=>d.getElementById(id).click(),change:(id,value)=>{const e=d.getElementById(id);if(e.type==='checkbox')e.checked=value;else e.value=value;e.dispatchEvent(new dom.window.Event('change',{bubbles:true}));},submit:id=>d.getElementById(id).dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}))};}
const graph=(ids,edges,start=ids[0])=>({meta:{start,title:'Fixture'},states:ids.map(id=>({id,label:String(id),viability:.5,notes:''})),transitions:edges.map(([from,to,p=1,dv=0])=>({from,to,p,dv,label:''}))});
const canonical=components=>components.map(c=>[...c].sort().join('|')).sort();
// Independent oracle: transitive closure, not an SCC implementation.
function reference(m,cutoff){const ids=m.states.map(s=>s.id),n=ids.length,index=new Map(ids.map((id,i)=>[id,i])),r=ids.map((_,i)=>ids.map((_,j)=>i===j));const active=m.transitions.filter(t=>t.p>0&&t.p>=cutoff);for(const t of active)r[index.get(t.from)][index.get(t.to)]=true;for(let k=0;k<n;k++)for(let i=0;i<n;i++)for(let j=0;j<n;j++)r[i][j]||=r[i][k]&&r[k][j];const assigned=new Set(),groups=[];for(let i=0;i<n;i++)if(!assigned.has(ids[i])){const g=ids.filter((_,j)=>r[i][j]&&r[j][i]);g.forEach(x=>assigned.add(x));groups.push(g);}const closed=groups.filter(c=>!active.some(t=>c.includes(t.from)&&!c.includes(t.to)));return{groups,closed,reachable:ids.filter((_,j)=>r[index.get(m.meta.start)][j])};}

test('all five original states, seven transitions, scores, notes and labels retained exactly',t=>{const {m}=ui(t);const original=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/phase-three-viability-baseline.json'),'utf8'));assert.deepEqual(clone(m.baseline()),original);assert.equal(original.states.length,5);assert.equal(original.transitions.length,7);});

test('SCCs, closed classes and reachability match transitive closure for all three-state directed graphs',t=>{const{m}=ui(t);for(let mask=0;mask<512;mask++){const edges=[];for(let i=0;i<3;i++)for(let j=0;j<3;j++)if(mask&(1<<(3*i+j)))edges.push([String(i),String(j),((i+j)%2)?.25:.75]);const input=graph(['0','1','2'],edges);for(const cutoff of [0,.5,1]){const expected=reference(input,cutoff),actual=m.analyse(m.normalizeModel(input),cutoff);assert.deepEqual(canonical(clone(actual.components)),canonical(expected.groups));assert.deepEqual(canonical(clone(actual.classes.map(c=>c.members))),canonical(expected.closed));assert.deepEqual([...actual.reachable].sort(),expected.reachable.sort());}}});

test('weights are normalised per source; zero weights never create exits or chances',t=>{const{m}=ui(t);const a=m.analyse(m.normalizeModel(m.baseline()));near(a.chances.get(m.edgeKey({from:'S1',to:'S2'})),.7);near(a.chances.get(m.edgeKey({from:'S1',to:'S4'})),.3);near(a.chances.get(m.edgeKey({from:'S2',to:'S3'})),1);const zero=m.normalizeModel(graph(['A','B'],[['A','B',0]])),r=m.analyse(zero,0);assert.equal(r.active.length,0);assert.equal(r.classes.length,2);assert.deepEqual([...r.reachable],['A']);for(const cutoff of [0,.1,1]){const a=m.analyse(m.normalizeModel(m.baseline()),cutoff);for(const s of m.baseline().states){const values=a.active.filter(t=>t.from===s.id).map(t=>a.chances.get(m.edgeKey(t)));if(values.length)near(values.reduce((x,y)=>x+y,0),1);}}});

test('terminal arrival stays in place without resetting, visits include start and stays, no phantom edges',t=>{const{m}=ui(t);const r=m.simulate(graph(['A','B','C'],[['A','B',1,-.1],['B','C',0]]),{steps:9,applyDv:true});assert.equal(r.current,'B');assert.equal(r.moves,1);assert.equal(r.holds,8);assert.deepEqual(clone(r.heat.node),{A:1,B:9});assert.equal(Object.values(r.heat.edge).reduce((a,b)=>a+b,0),1);near(r.model.states[1].viability,.4);assert.deepEqual(clone(r.path),['A','B','B','B','B','B','B','B','B','B']);});

test('deterministic cycle has exact visit, traversal and impact totals; input is not mutated',t=>{const{m}=ui(t);const input=graph(['A','B'],[['A','B',.2,.1],['B','A',.9,-.2]]),before=clone(input);const r=m.simulate(input,{steps:10,applyDv:true});assert.deepEqual(clone(input),before);assert.deepEqual(clone(r.heat.node),{A:6,B:5});assert.deepEqual(Object.values(r.heat.edge),[5,5]);near(r.model.states[0].viability,0);near(r.model.states[1].viability,1);assert.equal(r.moves+r.holds,r.steps);assert.equal(Object.values(r.heat.node).reduce((a,b)=>a+b,0),11);});

test('seeded walk is reproducible and empirical branching agrees with an independently specified 3:1 model',t=>{const{m}=ui(t);const input=graph(['A','B','C'],[['A','B',.75],['A','C',.25],['B','A',1],['C','A',1]]);const r=m.simulate(input,{steps:50000,seed:'distribution-check'});assert.deepEqual(clone(r),clone(m.simulate(input,{steps:50000,seed:'distribution-check'})));assert.equal(r.heat.node.A,25001);assert.equal(r.heat.node.B+r.heat.node.C,25000);assert.ok(Math.abs(r.heat.node.B/25000-.75)<.015);assert.notDeepEqual(clone(r.heat),clone(m.simulate(input,{steps:50000,seed:'different'}).heat));const job=m.walkJob(input,{steps:101});assert.throws(()=>job.result(),/incomplete/);while(!job.step(7)){}assert.deepEqual(clone(job.result()),clone(m.simulate(input,{steps:101})));});

test('valid legacy numeric IDs (including zero) preserve endpoints and canonical string IDs',t=>{const{m}=ui(t);const source=graph([0,1],[[0,1,.4]],0);source.layout={positions:[{id:0,x:0,y:0},{id:1,x:50,y:-50}]};const n=m.normalizeModel(source);assert.deepEqual(clone(n.states.map(s=>s.id)),['0','1']);assert.equal(n.transitions[0].from,'0');assert.equal(n.transitions[0].to,'1');assert.equal(n.meta.start,'0');assert.equal(n.layout.positions[0].id,'0');assert.deepEqual(clone(m.normalizeModel(n)),clone(n));});

test('invalid imports are atomic and reject destructive coercions, duplicate IDs/endpoints, unsupported fields and nonfinite values',t=>{const{m}=ui(t);const before=clone(m.snapshot());const mutations=[x=>x.states=[],x=>x.states.push({...x.states[0]}),x=>{x.states[0].id=1;x.states[1].id='1';},x=>x.states[0].viability=NaN,x=>x.states[0].viability='0.5',x=>x.states[0].viability=-.1,x=>x.states[0].id={},x=>x.states[0].label=7,x=>x.transitions[0].p=Infinity,x=>x.transitions[0].p=1.1,x=>x.transitions[0].dv=-2,x=>x.transitions[0].from='unknown',x=>x.transitions.push({...x.transitions[0]}),x=>x.transitions.push(null),x=>x.meta.start='missing',x=>x.states[0].extra='must not disappear',x=>x.extra={},x=>x.layout={positions:[{id:'S1',x:NaN,y:0}]},x=>x.layout={positions:[{id:'missing',x:0,y:0}]},x=>x.layout={positions:[{id:'S1',x:0,y:0},{id:'S1',x:1,y:1}]},x=>x.layout={positions:[{id:'S1',x:10001,y:0}]}];for(const mutate of mutations){const value=m.baseline();mutate(value);assert.throws(()=>m.normalizeModel(value));assert.throws(()=>m.importText(JSON.stringify(value)));assert.deepEqual(clone(m.snapshot()),before);}for(const text of ['', '{bad', 'x'.repeat(2*1024*1024+1)])assert.throws(()=>m.importText(text));assert.deepEqual(clone(m.snapshot()),before);});

test('text IDs, labels and notes remain inert; delimiter collisions do not merge transitions or prototype keys',async t=>{const{m,d}=ui(t);const input=graph(['__proto__','A->B','B','A','B->B'],[['A->B','B'],['A','B->B'],['__proto__','__proto__']],'__proto__');input.states[0].label='<img src=x onerror=alert(1)>';input.states[0].notes='</textarea><script>alert(1)</script>';m.importText(JSON.stringify(input));assert.equal(d.querySelector('#states-body img'),null);assert.match(d.querySelector('#states-body').textContent,/<img/);assert.notEqual(m.edgeKey(input.transitions[0]),m.edgeKey(input.transitions[1]));await m.runWalk();assert.equal(m.snapshot().heat.node.__proto__,251);assert.equal({}.polluted,undefined);m.undo();assert.equal(Object.keys(m.snapshot().heat.node).length,0);});

test('all five probe methods are deterministic, valid, nonmutating and implement their named operation',t=>{const{m}=ui(t);for(const type of ['v','p','add','rm','rew']){const input=m.baseline(),before=clone(input),r=m.perturb(input,{types:[type],seed:'method-check'});assert.deepEqual(clone(input),before);assert.deepEqual(clone(r),clone(m.perturb(input,{types:[type],seed:'method-check'})));assert.equal(r.type,type);assert.equal(r.changed,true);m.normalizeModel(r.model);if(type==='add')assert.equal(r.model.transitions.length,input.transitions.length+1);if(type==='rm')assert.equal(r.model.transitions.length,input.transitions.length-1);if(type==='rew'){const diffs=r.model.transitions.filter((x,i)=>JSON.stringify(x)!==JSON.stringify(input.transitions[i]));assert.equal(diffs.length,1);assert.ok(input.transitions.some(x=>x.from===diffs[0].from&&x.p===diffs[0].p&&x.dv===diffs[0].dv));}if(type==='v')assert.deepEqual(clone(r.model.transitions),clone(input.transitions));if(type==='p')assert.deepEqual(clone(r.model.states),clone(input.states));}const one=graph(['A'],[]);for(const type of ['add','rm','rew','p'])assert.equal(m.perturb(one,{types:[type]}).changed,false);assert.equal(m.perturb(one,{types:['v'],amp:0}).changed,false);assert.throws(()=>m.perturb(one,{types:[]}));});

test('bounds reject fractional, nonfinite and malformed run settings before any computation',t=>{const{m}=ui(t);for(const steps of [0,-1,1.5,50001,NaN,Infinity,'10'])assert.throws(()=>m.simulate(m.baseline(),{steps}));for(const cutoff of [-1,1.1,NaN,'0'])assert.throws(()=>m.simulate(m.baseline(),{cutoff}));assert.throws(()=>m.simulate(m.baseline(),{seed:'x'.repeat(201)}));assert.throws(()=>m.simulate(m.baseline(),{applyDv:1}));const large=graph(Array.from({length:201},(_,i)=>String(i)),[]);assert.throws(()=>m.normalizeModel(large));const dense=graph(Array.from({length:50},(_,i)=>String(i)),[]);dense.transitions=Array.from({length:2001},(_,i)=>({from:String(Math.floor(i/50)),to:String(i%50),p:1}));assert.throws(()=>m.normalizeModel(dense));});

test('UI edits, start, cutoff, perturbation, title, deletion and undo preserve usable navigation and expected semantics',t=>{const{m,d,click,change,submit}=ui(t);d.querySelector('#states-body button').click();assert.equal(d.activeElement.id,'edit-label');d.getElementById('edit-label').value='Renamed state';d.getElementById('edit-score').value='.9';submit(d.querySelector('#inspector form').id='edit-form');assert.equal(m.model().states[0].label,'Renamed state');assert.equal(d.activeElement.id,'edit-label');click('undoBtn');assert.equal(m.model().states[0].label,'Baseline Ops');change('startSelect','S3');assert.equal(m.model().meta.start,'S3');click('undoBtn');assert.equal(m.model().meta.start,'S1');change('pCut','.31');assert.match(d.getElementById('classes').textContent,/S3.*terminal/);click('undoBtn');assert.equal(m.snapshot().cutoff,0);d.getElementById('title').value='Changed';click('save-title');assert.equal(m.model().meta.title,'Changed');click('undoBtn');assert.equal(m.model().meta.title,m.baseline().meta.title);d.querySelector('#states-body button').click();const remove=[...d.querySelectorAll('#inspector button')].find(e=>e.textContent.startsWith('Remove'));remove.click();assert.equal(m.model().states.length,4);assert.ok(m.model().transitions.every(e=>e.from!=='S1'&&e.to!=='S1'));click('undoBtn');assert.equal(m.model().states.length,5);});

test('walk cancellation is transactional and an ordinary completed run is undoable with exact counts',async t=>{const{m,d,click,change}=ui(t);d.getElementById('walkSteps').value=50000;const before=clone(m.snapshot()),pending=m.runWalk();assert.equal(d.getElementById('walkBtn').disabled,true);m.cancel();await pending;assert.deepEqual(clone(m.snapshot()),before);assert.match(d.getElementById('status').textContent,/cancelled/);assert.equal(d.getElementById('walkBtn').disabled,false);d.getElementById('walkSteps').value=17;await m.runWalk();assert.equal(Object.values(m.snapshot().heat.node).reduce((a,b)=>a+b,0),18);assert.match(d.getElementById('walk-result').textContent,/17 steps/);m.undo();assert.deepEqual(clone(m.snapshot()),before);await m.runWalk();change('pCut','.3');assert.equal(Object.keys(m.snapshot().heat.node).length,0);click('undoBtn');assert.equal(Object.values(m.snapshot().heat.node).reduce((a,b)=>a+b,0),18);});

test('JSON UI import/export roundtrip, failed import preservation, structural additions and limits',t=>{const{m,d,click,submit}=ui(t);click('show-json');const before=m.snapshot();d.getElementById('jsonText').value='{invalid';click('import-json');assert.match(d.getElementById('status').textContent,/JSON|property|Expected/);assert.deepEqual(clone(m.snapshot()),clone(before));d.getElementById('new-id').value='S6';d.getElementById('new-label').value='Recovery';submit('add-state');assert.equal(m.model().states.length,6);d.getElementById('new-from').value='S5';d.getElementById('new-to').value='S6';submit('add-edge');assert.equal(m.model().transitions.length,8);click('show-json');const saved=d.getElementById('jsonText').value;click('resetBtn');assert.equal(m.model().states.length,5);d.getElementById('jsonText').value=saved;click('import-json');assert.equal(m.model().states.length,6);assert.deepEqual(clone(m.exportModel()),JSON.parse(saved));});

test('graph supports self loops, keyboard editing, layout export, zoom, fallback and labelled native controls',t=>{const{m,d,dom,click}=ui(t,{graph:true});assert.equal(d.querySelectorAll('.node').length,5);assert.equal(d.querySelectorAll('.edge').length,7);const first=d.querySelector('.node');first.dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.equal(d.activeElement.id,'edit-label');click('showEdgeLabels');click('focusAttractorsBtn');click('zoomIn');click('zoomOut');m.importText(JSON.stringify(graph(['A'],[['A','A',1]])));assert.equal(d.querySelectorAll('.node').length,1);assert.match(d.querySelector('.edge').getAttribute('d'),/C/);const n=d.querySelector('.node'),before=m.exportModel().layout.positions[0].x;n.dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));near(m.exportModel().layout.positions[0].x,before+10);for(const input of [...d.querySelectorAll('input,select,textarea')])assert.ok(input.labels.length>0,`${input.id} lacks a label`);assert.equal(d.querySelectorAll('.table-scroll[tabindex="0"]').length,2);});

test('imported finite layout is applied exactly and restored by undo; keyboard movement survives JSON export',t=>{const{m,d,dom}=ui(t,{graph:true});const input=graph(['A','B'],[['A','B']]);input.layout={positions:[{id:'A',x:125,y:150},{id:'B',x:400,y:450}]};m.importText(JSON.stringify(input));m.destroy();assert.deepEqual(clone(m.exportModel().layout),input.layout);const node=d.querySelector('.node');node.dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));assert.equal(m.exportModel().layout.positions[0].y,160);const changed=clone(m.exportModel());m.importText(JSON.stringify(graph(['C'],[])));m.undo();m.destroy();assert.deepEqual(clone(m.exportModel()),changed);});

test('file import failures and oversized files keep the current model; a slow read cannot overwrite intervening edits',async t=>{const{m,d,dom,click}=ui(t);let reader;dom.window.FileReader=class{constructor(){reader=this;}readAsText(){}};const input=d.getElementById('importFile');const choose=file=>{Object.defineProperty(input,'files',{configurable:true,value:[file]});input.dispatchEvent(new dom.window.Event('change',{bubbles:true}));};const before=clone(m.snapshot());choose({size:3*1024*1024});await Promise.resolve();assert.match(d.getElementById('status').textContent,/exceeds/);assert.deepEqual(clone(m.snapshot()),before);choose({size:3});reader.result='{bad';reader.onload();await Promise.resolve();await Promise.resolve();assert.match(d.getElementById('status').textContent,/Import failed/);assert.deepEqual(clone(m.snapshot()),before);choose({size:200});d.getElementById('title').value='Newer title';click('save-title');reader.result=JSON.stringify(graph(['late'],[]));reader.onload();await Promise.resolve();await Promise.resolve();assert.equal(m.model().meta.title,'Newer title');assert.match(d.getElementById('status').textContent,/changed while reading/);});

test('normal text undo is left to the browser; model undo shortcut works outside text fields',t=>{const{m,d,dom,click}=ui(t);d.getElementById('title').value='Edit';click('save-title');const event=new dom.window.KeyboardEvent('keydown',{key:'z',ctrlKey:true,bubbles:true,cancelable:true});d.getElementById('title').dispatchEvent(event);assert.equal(event.defaultPrevented,false);assert.equal(m.model().meta.title,'Edit');const elsewhere=new dom.window.KeyboardEvent('keydown',{key:'z',ctrlKey:true,bubbles:true,cancelable:true});d.getElementById('main').dispatchEvent(elsewhere);assert.equal(elsewhere.defaultPrevented,true);assert.equal(m.model().meta.title,m.baseline().meta.title);});
