'use strict';const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('../tools/library-apps/node_modules/jsdom');const dir=path.join(__dirname,'../library/apps/reading-project-evidence'),data=require(dir+'/data.js'),M=require(dir+'/model.js');
function page(){const d=new JSDOM(fs.readFileSync(dir+'/index.html','utf8'),{url:'https://example.test/library/apps/reading-project-evidence/',runScripts:'outside-only'});for(const f of ['data.js','model.js','app.js'])d.window.eval(fs.readFileSync(dir+'/'+f,'utf8'));return d;}
test('the original four-theme structure has 73 distinct labels, 62 annotations and unambiguous parent paths',()=>{const a=M.flatten(data.themes);assert.equal(data.themes.length,4);assert.equal(a.length,73);assert.equal(a.filter(n=>n.annotation).length,62);assert.equal(new Set(a.map(n=>n.id)).size,73);for(const n of a)for(const child of n.children)assert.equal(child.parent,n.id);const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/phase-three-evidence-retention.json'),'utf8'));assert.deepEqual(a.map(n=>({label:n.label,annotation:n.annotation})),fixture.codes);assert.deepEqual(data.records.map(r=>Object.fromEntries(Object.keys(fixture.records[0]).map(k=>[k,r[k]]))),fixture.records);});
test('all 22 records keep separate statement identities, source URLs and numerical legacy outputs',()=>{assert.equal(data.records.length,22);assert.equal(data.records.filter(r=>r.source_type==='news').length,10);assert.equal(data.records.filter(r=>r.source_type==='social').length,12);assert.equal(new Set(data.records.map(r=>r.id)).size,22);const g=M.graph(data.records);assert.equal(g.nodes.length,44);assert.equal(g.edges.length,22);assert.equal(new Set(g.nodes.map(n=>n.id)).size,44);for(const e of g.edges){assert.ok(g.nodes.some(n=>n.id===e.source));assert.ok(g.nodes.some(n=>n.id===e.target));}assert.equal(data.records.filter(r=>r.source_check.startsWith('Text and')).length,2);assert.ok(data.records.filter(r=>r.source_type==='social').every(r=>r.date===null));});
test('summaries follow exact selected records; empty groups have no invented zero average',()=>{for(const type of ['all','news','social'])for(const stance of ['all','Supporter','Opponent','Neutral'])for(const q of ['','hazard','purpose','nothing-match']){const a=M.select(data.records,{query:q,type,stance});const expected=data.records.filter(r=>(type==='all'||r.source_type===type)&&(stance==='all'||r.legacy_stance===stance)&&(!q||[r.id,r.source_type,r.source_label,r.date||'Unknown',r.url,r.stakeholder,r.stakeholder_kind,r.stance_role,r.legacy_stance,r.intention,r.text,r.polarity,r.subjectivity,r.sentiment,r.lex_score,r.stance_note].join(' ').toLowerCase().includes(q)));assert.deepEqual(a.map(r=>r.id).sort(),expected.map(r=>r.id).sort());for(const s of M.summaries(a)){const rows=expected.filter(r=>r.legacy_stance===s.role);assert.equal(s.count,rows.length);assert.equal(s.polarity,rows.length?rows.reduce((a,r)=>a+r.polarity,0)/rows.length:null);}}const zero=M.summaries([]);assert.ok(zero.every(x=>x.polarity===null&&x.lex===null));});
test('dates and numeric sorting are defined, stable and leave inputs unchanged',()=>{const before=JSON.stringify(data.records);for(const sort of ['polarity','lex']){const rows=M.select(data.records,{sort}),key=sort==='lex'?'lex_score':sort;for(let i=1;i<rows.length;i++)assert.ok(rows[i-1][key]>=rows[i][key]);}const dates=M.select(data.records,{sort:'date'});assert.ok(dates.slice(0,10).every(r=>r.date));assert.ok(dates.slice(10).every(r=>!r.date));assert.equal(JSON.stringify(data.records),before);});
test('actual tree controls expose all annotations by keyboard and preserve source context in search',()=>{const dom=page(),d=dom.window.document;assert.equal(d.querySelectorAll('button[data-code]').length,73);assert.equal(d.querySelectorAll('.annotation').length,62);const b=d.querySelector('button[aria-controls]');b.click();assert.equal(b.getAttribute('aria-expanded'),'true');assert.equal(d.getElementById(b.getAttribute('aria-controls')).hidden,false);d.getElementById('collapse-all').click();assert.ok([...d.querySelectorAll('details.theme')].every(x=>!x.open));d.getElementById('code-filter').value='MRI';d.getElementById('code-filter').dispatchEvent(new dom.window.Event('input'));assert.equal(d.querySelectorAll('.matching').length,1);assert.equal([...d.querySelectorAll('details.theme')].filter(x=>!x.hidden).length,1);dom.window.close();});
test('actual filters update chart, rows and pair graph together and clear stale selected detail',()=>{const dom=page(),d=dom.window.document;d.querySelector('#records button').click();assert.match(d.getElementById('record-detail').textContent,/news_01/);d.getElementById('record-query').value='hazard';d.getElementById('record-query').dispatchEvent(new dom.window.Event('input'));assert.equal(d.querySelectorAll('#records tbody tr').length,2);assert.equal(d.querySelectorAll('#distribution circle').length,2);assert.equal(d.querySelectorAll('#intention-graph .pair').length,2);assert.doesNotMatch(d.getElementById('record-detail').textContent,/news_01/);d.querySelector('#intention-graph button').click();assert.match(d.getElementById('record-detail').textContent,/does not establish opposition/);d.getElementById('record-query').value='no match abc';d.getElementById('record-query').dispatchEvent(new dom.window.Event('input'));assert.equal(d.querySelectorAll('#records tbody tr').length,0);assert.match(d.getElementById('averages').textContent,/No records/);d.getElementById('reset-records').click();assert.equal(d.querySelectorAll('#records tbody tr').length,22);dom.window.close();});
test('export captures current selection with full coding tree and evidence boundary, then invalidates on filter changes',()=>{const dom=page(),d=dom.window.document;d.getElementById('record-type').value='social';d.getElementById('record-type').dispatchEvent(new dom.window.Event('change'));d.getElementById('export').click();const out=JSON.parse(d.getElementById('export-text').value);assert.equal(out.selectedRecords.length,12);assert.equal(out.themes.length,4);assert.match(out.evidenceBoundary,/not verified findings/);assert.equal(d.getElementById('download').disabled,false);d.getElementById('reset-records').click();assert.equal(d.getElementById('download').disabled,true);assert.equal(d.getElementById('export-text').value,'');dom.window.close();});
test('search retains legacy sentiment, date, numeric and URL fields',()=>{
 assert.deepEqual(M.select(data.records,{query:'negative'}).map(r=>r.id),['news_02','news_10','social_03']);
 assert.equal(M.select(data.records,{query:'2024'}).length,10);
 assert.equal(M.select(data.records,{query:'Unknown'}).length,12);
 assert.deepEqual(M.select(data.records,{query:'-0.1875'}).map(r=>r.id),['news_02','news_10']);
 assert.deepEqual(M.select(data.records,{query:'0.9750000000000001'}).map(r=>r.id),['news_06']);
 assert.deepEqual(M.select(data.records,{query:'https://journalrecord.com/2024/06/04/'}).map(r=>r.id),['news_03','news_04']);
});
test('interpretation pairs display stance in text and colour; inspector retains every supplied score',()=>{
 const dom=page(),d=dom.window.document;
 for(const record of data.records){const pair=[...d.querySelectorAll('#intention-graph .pair')].find(p=>p.querySelector('button').textContent.startsWith(record.id+' · '));assert.equal(pair.dataset.stance,record.legacy_stance);assert.equal(pair.querySelector('.stance-label').textContent,'Original label: '+record.legacy_stance);}
 const social=[...d.querySelectorAll('#intention-graph .pair')].find(p=>p.querySelector('button').textContent.startsWith('social_01 · '));social.querySelector('button').click();const detail=d.querySelector('#record-detail').textContent;
 assert.match(detail,/Recorded polarity: 0.303/);assert.match(detail,/Recorded subjectivity: 0.712/);assert.match(detail,/Recorded lexicon score: 1/);assert.match(detail,/Legacy sentiment: positive/);
 const styles=fs.readFileSync(dir+'/style.css','utf8');for(const stance of ['Supporter','Opponent','Neutral'])assert.ok(styles.includes('[data-stance="'+stance+'"]'));
 const readme=fs.readFileSync(dir+'/README.md','utf8');for(const name of ['grounded-theory-approach.html','legends_tower_sentiment_report.html'])assert.ok(readme.includes('https://github.com/lawrencerowland/Project-web-apps/blob/cd0528939fd0e1f5de1df7cda9930785349e4946/web_apps/'+name));
 dom.window.close();
});
